runltp: !mux
    script: 'runltp'
    cap_bounds:
        args: '-f cap_bounds'
    crashme:
        args: '-f crashme'
    crypto:
        args: '-f crypto'
    cve:
        args: '-f cve'
    ima:
        args: '-f ima'
    securebits:
        args: '-f securebits'
    tpm_tools:
        args: '-f tpm_tools'
